### ISSUE TITLE
404 on jar install page

### ISSUE THREAD

**Issue by metaproph3t** [makolabs-xyz/arcana#14]
I get a 404 on the [page](https://www.arcana.markets/arcana-1.0.jar) linked for installing Arcana

**Comment by kizmt** [comment]
Thanks for pointing this out @metaproph3t - we ran into a couple of issues when migrating domains.

You should now be able to navigate to https://www.arcana.markets/ and click the 'Download' button.

Let me know how you go!

Will also amend the URL in the readme.

![Screenshot 2023-10-27 105228](https://github.com/makolabs-xyz/arcana/assets/90412655/34299b4a-75ad-4bcd-9e8b-505ac1272ea8)

**Comment by kizmt** [comment]
This has been resolved in commit fcc2d4c.

Closing 🤝
